class _Tensor:
    def __init__(self, size: int) -> None: ...
    @property
    def size(self) -> int: ...
    def copy_from_list(self, data: list[float]) -> None: ...
    def to_list(self) -> list[float]: ...
    def _add(self, other: _Tensor) -> _Tensor: ...