from numpy.typing import NDArray

class _Tensor:
    def __init__(self, size: int) -> None: ...
    @property
    def _size(self) -> int: ...
    def _copy_from_list(self, data: list[float]) -> None: ...
    def _to_list(self, shape: tuple[int, ...]) -> list[float] | list[list[float]]: ...
    def _to_np(self) -> NDArray: ...

# tensor operators
def _add_tensor(a: _Tensor, b: _Tensor) -> _Tensor: ...
def _sub_tensor(a: _Tensor, b: _Tensor) -> _Tensor: ...
def _mul_tensor(a: _Tensor, b: _Tensor) -> _Tensor: ...
def _truediv_tensor(a: _Tensor, b: _Tensor) -> _Tensor: ...
def _max_tensor(a: _Tensor, b: _Tensor) -> _Tensor: ...
def _min_tensor(a: _Tensor, b: _Tensor) -> _Tensor: ...
def _gt_tensor(a: _Tensor, b: _Tensor) -> _Tensor: ...

# scalar operators
def _add_scalar(a: _Tensor, b: float) -> _Tensor: ...
def _sub_scalar(a: _Tensor, b: float) -> _Tensor: ...
def _rsub_scalar(a: _Tensor, b: float) -> _Tensor: ...
def _mul_scalar(a: _Tensor, b: float) -> _Tensor: ...
def _truediv_scalar(a: _Tensor, b: float) -> _Tensor: ...
def _rtruediv_scalar(a: _Tensor, b: float) -> _Tensor: ...
def _max_scalar(a: _Tensor, b: float) -> _Tensor: ...
def _min_scalar(a: _Tensor, b: float) -> _Tensor: ...
def _gt_scalar(a: _Tensor, b: float) -> _Tensor: ...

# unary operators
def _negate(a: _Tensor) -> _Tensor: ...
def _exponent(a: _Tensor) -> _Tensor: ...

# unary trig operators
def _sin(a: _Tensor) -> _Tensor: ...
def _cos(a: _Tensor) -> _Tensor: ...
def _tan(a: _Tensor) -> _Tensor: ...
def _ctg(a: _Tensor) -> _Tensor: ...

# unary trig hyperbolic operators
def _sinh(a: _Tensor) -> _Tensor: ...
def _cosh(a: _Tensor) -> _Tensor: ...
def _tanh(a: _Tensor) -> _Tensor: ...
def _ctgh(a: _Tensor) -> _Tensor: ...

# transpose
def _transpose(a: _Tensor, n: int, m: int) -> _Tensor: ...

# misc operators
def _matmul(a: _Tensor, b: _Tensor, n: int, m: int, k: int) -> _Tensor: ...
def _from_numpy(a: NDArray) -> _Tensor: ...
