from __future__ import annotations
from typing import List, Tuple, Union

from numpy.typing import NDArray

class _Tensor:
    def __init__(self, size: int) -> None: ...
    @property
    def _size(self) -> int: ...
    def _copy_from_list(self, data: List[float]) -> None: ...
    def _to_list(
        self, shape: Tuple[int, ...]
    ) -> Union[List[float], List[List[float]]]: ...
    def _to_np(self) -> NDArray: ...

def _add(a: _Tensor, b: _Tensor) -> _Tensor: ...
def _subtract(a: _Tensor, b: _Tensor) -> _Tensor: ...
def _multiply_elementwise(a: _Tensor, b: _Tensor) -> _Tensor: ...
def _negate(tensor: _Tensor) -> _Tensor: ...
def _matmul(a: _Tensor, b: _Tensor, n: int, m: int, k: int) -> _Tensor: ...
def _from_numpy(a: NDArray) -> _Tensor: ...
def _max_tensor(a: _Tensor, b: _Tensor) -> _Tensor: ...
def _max_scalar(a: _Tensor, b: float) -> _Tensor: ...
